FROM node:14-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --production

COPY ./src ./src
COPY ./public ./public

RUN npm run build

FROM nginx:latest

WORKDIR /usr/share/nginx/html

COPY --from=builder /usr/src/app/build .

ENTRYPOINT ["nginx", "-g", "daemon off;"]
